from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture
document.add_picture(
    'suit.png', 
    width=Inches(2.0)
)

# name phone number and email details
speak(
    'Hi, my name is El, Welcome! Let me help you build your CV'
)
speak(
    'What is your name? '
)
name = input(
    'What is your name? '
)
speak(
    'Hello ' + name + ' How are you today? '
)
speak(
    'input your phone number? '
)
phone_number = input(
    'What is your phone number? '
)
speak(
    'input your email address? '
)
email = input(
    'What is your email? '
)

document.add_paragraph(
    name + ' | ' + phone_number + ' | ' + email
)

# about me
document.add_heading(
    'About me'
)
speak(
    name + 'Tell me about yourself '
)
about_me = input(
    'Tell me about yourself? '
)
document.add_paragraph(about_me)

# work experience
document.add_heading(
    'Work Experience'
)
p = document.add_paragraph()

speak(
    'Add your work experience '
)

speak(
    'Where did you work? '
)
company = input(
    'Enter company '
)
speak(
    'When did you start working at ' + company
)
from_date = input(
    'From Date '
)
speak(
    'when did you stop working at ' + company
)
to_date = input(
    'To Date '
)

p.add_run(company + ' ' ).bold = True
p.add_run(from_date + '-' + to_date + '\n' ).italic = True

speak(
    'What did you do at ' + company
)
experience_details = input(
    'Describe your experience at ' + company + ' '
)
p.add_run(experience_details)

# more experiences

while True:
    speak(
    'Do you have more experiences? Yes or No '
)
    has_more_experiences = input(
        'Do you have more experiences? Yes or No '
    )
    if has_more_experiences.lower() == 'yes':
        p = document.add_paragraph()

        speak(
            'Where did you work? '
        )
        company = input(
            'Enter company '
        )

        speak(
            'When did you start working at ' + company
        )
        from_date = input(
            'From Date '
        )

        speak(
            'when did you stop working at ' + company
        )
        to_date = input(
            'To Date '
        )

        p.add_run(company + ' ' ).bold = True
        p.add_run(from_date + '-' + to_date + '\n' ).italic = True

        speak(
            'What did you do at ' + company
        )
        experience_details = input(
            'Describe your experience at ' + company + ' '
        )
        p.add_run(experience_details)
    else:
        break

# Skills
document.add_heading(
    'Skills'
)

speak(
    'What skills do you have? '
)

speak(
    'Input a Skill '
)
skill = input(
    'Enter Skill '
)
p = document.add_paragraph(skill)
p.style = 'List Bullet'

# more skills

while True:
    speak(
    'Do you have more skills? Yes or No '
)
    has_more_skills = input(
        'Do you have more skills? Yes or No '
    )
    if has_more_skills.lower() == 'yes':
        p = document.add_paragraph()

        speak(
            'Input a Skill '
        )
        skill = input(
            'Enter Skill '
        )

        p = document.add_paragraph(skill)
        p.style = 'List Bullet'
    else:
        break

speak(
    "Thank you for using El's CV Builder,  it was nice having you here"
)    

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'cv generated by ElTech'

document.save('cv.docx')